package com.xeroKarao.demo.service;

import com.xeroKarao.demo.dto.FileDto;
import com.xeroKarao.demo.exception.GCPFileUploadException;
import com.xeroKarao.demo.model.FileData;
import com.xeroKarao.demo.repository.FileRepo;
import com.xeroKarao.demo.util.BucketUtil;
import org.apache.coyote.BadRequestException;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@Service
public class FileServiceImpl implements FileService{

    private final FileRepo repo;

    private final BucketUtil dataBucketUtil;

    public FileServiceImpl(FileRepo repo, BucketUtil bucketUtil) {
        this.repo = repo;
        this.dataBucketUtil = bucketUtil;
    }

    //Uploading The File On GCP
    //Storing thier metadata in the database
    public List<FileData> uploadFile(MultipartFile[] files) {

        List<FileData> inputFiles = new ArrayList<>();
        Arrays.asList(files).forEach(file -> {
            String originalFileName = file.getOriginalFilename();
            if(originalFileName == null){
                try {
                    throw new BadRequestException("Original file name is null");
                } catch (BadRequestException e) {
                    throw new RuntimeException(e);
                }
            }
            Path path = new File(originalFileName).toPath();

            try {
                String contentType = Files.probeContentType(path);
                FileDto fileDto = dataBucketUtil.uploadFile(file, originalFileName, contentType);

                if (fileDto != null) {
                    //This is adding the url in database that is generated by the cloud
                    inputFiles.add(new FileData(fileDto.getFileName(), fileDto.getFileUrl()));
                    }
            } catch (Exception e) {

                throw new GCPFileUploadException("Error occurred while uploading");
            }
        });

        //Saving the Url in the database
        repo.saveAll(inputFiles);

        return inputFiles;
    }
}
